### ISSUE TITLE
Issues with "Remove From Feed for YouTube"

### ISSUE THREAD

**Issue by Staminist** [JeromeDane/YouTube-Remove-From-Feed-Button#3]
Just the other day, I was looking through my subscription box on YT and as always I clicked the 'x' to remove the ones I watched or else. And it did remove it, until I refreshed the page - the links of the videos that should of been removed were there again. 
Must be something new on YouTube's side, because the AddOn worked perfectly and I LOVE it! :)

I would be really thankful if you could look into this problem.

Thank you again and cheers!

**Comment by JeromeDane** [comment]
I'm guessing this has been fixed already, since it seems to be working now, but please let me know if not. Sorry I didn't get this closed until now.
