### ISSUE TITLE
Youtube subscription page updated with grid view

### ISSUE THREAD

**Issue by mvaleriani** [JeromeDane/YouTube-Remove-From-Feed-Button#8]
I would love you 4ever if you updated the extension to work with it!

**Comment by JeromeDane** [comment]
Will see what I can do over the next few days ... :bulb:

**Comment by JeromeDane** [comment]
Should be fixed in v0.7.0. Please update and let me know if it's still not working.

**Comment by Zairei** [comment]
Still cant remove all after X'ing them and refreshing. It just comes back.

**Comment by JeromeDane** [comment]
@Zairei are you sure it doesn't go away after a minute? I've found that the YouTube servers can sometimes take a while to register the fact that a video has been marked as hidden. It may also have trouble if there are network issues and you click the (x) button on a lot of videos very, very quickly. If it's still giving you trouble, would you create a separate issue with as much details about your system as possible?
